### ISSUE TITLE
Game crashing with "evaluated component 0x0 does not exist any more" errors

### ISSUE THREAD

**Issue by dephekt** [kuertee/x4-mod-da-ku-ai-tweaks#10]
I recently started having my game crash a few minutes into loading a save. I can consistently replicate the crash. I turned on debug logging when launching X4, then started tailing the log file while X4 loads my save. A few minutes after the save loads, I see the following being spammed in the log just as the game crashes:

```
[=ERROR=] 987342.45 Error in AI order Escort<0x24aa> on object 0x47484: Evaluated component 0x0 does not exist any more
* Expression: @$kAAIT_orderLocation_space
```
I did a git grep for that expression and it seems to be [implicating this](https://github.com/kuertee/x4-mod-da-ku-ai-tweaks/blob/master/aiscripts/order.fight.escort.xml#L69) but I'm not sure how to debug the issue further to find out where the problem really is without understanding more about how everything is implemented here.

I'm wondering if you have any ideas on what the problem is or how to do any further debugging to help narrow down the specific problematic condition that is triggering the crash (and how I might fix it before the crash)?

**Comment by kuertee** [comment]
Hi! That location tag has no effect on the logic of the AI. The map uses that tag to plot the order's destination.

I did find a weird bug that caused my game to hang. The game was running but it was unresponsive. And there were no logged errors. It looked like it was stuck in an infinite loop.

After many days of removing and then re-adding back files and code, I tracked it down to "order.move.recon.xml".

"order.move.recon.xml" has been unchanged since June 2022. And it never caused a problem. I think my changes from the last release affected something else that then indirectly affected it. After disabling it I was able to continue my game. I disabled it for the next release. Can you delete that file from the mod's folder and then try your game again, please?

If that doesn't solve the problem, can you send me at kuertee@gmail.com a debug log file as described in my read-me - i.e. not deadair's read-me? Or send me a saved-game. You can use wetransfer file service for large file transfers.

I'm hoping to get a release out early in Feb. I'm deciding at the moment whether to release an update for the base game's 5.1 version or just go directly to its 6.x version.

**Comment by dephekt** [comment]
> I did find a weird bug that caused my game to hang. The game was running but it was unresponsive. And there were no logged errors. It looked like it was stuck in an infinite loop.

This is actually what happens. Saying it crashed was a poor choice of words on my part. The game cursor image continues to show as I move the cursor around, the game audio continues playing, but everything else is frozen. The X4 process itself continues running until I send a SIGTERM or SIGKILL to it. So this sounds really similar to the behavior you're describing.

>  I disabled it for the next release. Can you delete that file from the mod's folder and then try your game again, please?

Will give this a try right now and report back. My grand solution was just going to disable the mod, allow the game to process for 5-10 minutes (to get past whatever behavior one of my fleet ships is doing somewhere that ultimately triggers this after 2-3 minutes in from my current save point) and then save and turn the mod back on and hope I'm past whatever was triggering the issue. I've been using the mod for several weeks without issues.

If it still happens I'll send you the save file, since I was able to reliably replicate the behavior across Windows and Linux within a few minutes after loading up the save and without doing any complicated replication steps.

**Comment by dephekt** [comment]
> "order.move.recon.xml" has been unchanged since June 2022. And it never caused a problem. I think my changes from the last release affected something else that then indirectly affected it. After disabling it I was able to continue my game. I disabled it for the next release. Can you delete that file from the mod's folder and then try your game again, please?

This seems to have worked. I've been playing for 10-15 minutes now and the game hasn't stalled. I'm way past the point where it would have by now. Really appreciate the quick turnaround, now I don't have to do a bunch of gymnastics trying to fix it myself lol

**Comment by kuertee** [comment]
Nice! I experienced that bug back in late Nov 2022. But I got very busy in Dec and Jan that I wasn't able to do anything about it until the last couple of weeks.

It's a rare bug. And has no DIRECT effect on any ships that are in attack orders. And the infinite loop (which is obviously what is happening) is not logged in any of my debugging comments. It took me several days to narrow it down.

Thanks for the bug report!
