### ISSUE TITLE
SCA stations getting overwhelmed

### ISSUE THREAD

**Issue by Machicooli** [kuertee/x4-mod-da-ku-ai-tweaks#9]
Since I installed this mod, SCA stations are getting attacked within the first hour of a new game and many getting destroyed by fleets from ARG and PAR. Silent Witness XI & XII are then quickly claimed by ARG and Nopileos Fortune VI and II either by PAR or TEL.
This makes the Hatikvah plot missions a bit more difficult since the last holdout stations are usually located in the ends of Nopileos Fortune II and it also gives less options to claim an unclaimed sector for the player faction.

The only other mod I installed that might change the NPC factions behavior is [DeadAir Gate](https://github.com/DeadAirRT/deadairgate) 0.90 which adds some defense to important stations (I don't know which ones), adds a few gates connections and removes highways.

**Comment by kuertee** [comment]
That's unusual. There are no changes to the faction's goal AI that would make them more or less aggressive to any. I think what you're experiencing is simply due to the universe generated in that game. Take it as an opportunity to help SCA.

I'll assign this to deadair to see if he's got ideas.

Here are the changes made to the faction goal AI. And none of them affects the faction's aggressiveness:
hold space ai:
<?xml version='1.0' encoding='utf-8'?>
<diff>
  <replace sel="/mdscript/cues/cue[@name='Start']/actions/find_cluster_in_range[@name='$LocalClusters']/@maxdistance">if $Faction == faction.xenon then 2 else 3</replace>
  <replace sel="/mdscript/cues/cue[@name='Start']/cues/cue[@name='EvaluateState']/actions/do_else/do_for_each[@name='$DesiredSubgoalsKey']/do_if[@value='$DesiredSubgoalAmount gt 0']/do_all[@exact='$DesiredSubgoalAmount']/do_elseif/do_if[@value='$ConstructionPlan']/do_if[@value='$StationMacro']/get_safe_pos[@max='100km']/@max">40km</replace>
</diff>

invade space:
<?xml version='1.0' encoding='utf-8'?>
<diff>
  <replace sel="/mdscript/cues/cue[@name='Start']/actions/find_cluster_in_range[@name='$LocalClusters']/@maxdistance">if $Faction == faction.xenon then 2 else 3</replace>
</diff>

**Comment by Machicooli** [comment]
Tried a new game without the mod (but DeadAir Gate still on) and let it play for about 3 hours but since I don't use any cheat mod I could not observe beyond the Silent Witness sectors,
AI is still somewhat aggressive and attacking SCA stations but they are way less effective at it. The big difference was in fleet size and ship types and the (or rather absence of) distance they kept with the stations they were attacking.

My assumption is that DeadAir Gate makes the initial fleets somewhat "stranded" in the sectors they are spawned because of the absence of highways and then aren't sent to the XEN or HOP fronts, so they are redirected to the closest next best threat which are the mostly undefended SCA stations in friendly or unclaimed space. This mod then makes the fleets especially effective at destroying them because they stay out of range of most of the stations defenses.

I'll try re-enabling this mod and disabling DeadAir Gate tomorrow in a new game to see if some of my assumption is correct.

**Comment by DeadAirRT** [comment]
Deadair Gate enables logic in those sectors. Without the change those sectors will forever remain neutral which seems absolutely silly to me; I'm not trying to keep the universe stagnant and player centric. If you want them to remain neutral, you can change the true to false in deadairgate/libraries/mapdefaults.xml.
